# PROJEKT
## ZASTOSOWANIE JĘZYKA PYTHON W DATA SCIENCE
ALEKSANDER GLEGOŁA  
73068  
VISTULA

# 1. Import bibliotek

In [1]:
# instalacja bibliotek gdyby nie były zainstalowane
# !pip install transformers torch scikit-learn pandas

In [2]:
# import potrzebnych bibliotek
import pandas as pd
import numpy as np
from transformers import pipeline
from sklearn.metrics.pairwise import cosine_similarity
import json
import random

# 2. Import danych

In [3]:
# wczytywanie danych
# źródło: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata?resource=download&select=tmdb_5000_movies.csv
# plik został umieszczony na githubie
url = 'https://raw.githubusercontent.com/AleksanderGlegola/DataScienceProject/refs/heads/main/tmdb_5000_movies.csv'
df = pd.read_csv(url)
df.head() # sprawdzenie czy dane się wczytały

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

# 3. Analiza

In [4]:
# analiza
shape = df.shape                    # wymiary
column_names = df.columns           # nazwy kolumn
types = df.dtypes                   # typy danych
number = df.count().sort_values()   # liczba rekordów
missing_counts = df.isnull().sum()  # liczba pustych komórek
print(f"\
Wymiary: \n{shape}\n\n\
Kolumny: \n{column_names}\n\n\
Typy: \n{types}\n\n\
Uzupełnione pola: \n{number}\n\n\
Liczba brakujących wartości: \n{missing_counts}")

Wymiary:
(4803, 20)

Kolumny:
Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

Typy:
budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

Uzupełnione pola:
homepage                1712
tagline                 3959
overview                4800
runtime                 4801
release_date            4802
id                      4803
genres                  4803
keywords                4803
original_title          4803
original_language       4803
production_companies    4803
popularity              4803
production_countries    4803
revenue                 4803
spoken_languages        4803
budget                  4803
status                  4803
title                   4803
vote_average            4803
vote_count              4803
dtype: int64

Liczba brakujących wartości:
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [5]:
df[['title', 'genres', 'overview']][0:10] # kolumny uzyte w projekcie

,title,genres,overview
0,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...
4,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca..."
5,Spider-Man 3,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",The seemingly invincible Spider-Man goes up ag...
6,Tangled,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",When the kingdom's most wanted-and most charmi...
7,Avengers: Age of Ultron,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",When Tony Stark tries to jumpstart a dormant p...
8,Harry Potter and the Half-Blood Prince,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","As Harry begins his sixth year at Hogwarts, he..."
9,Batman v Superman: Dawn of Justice,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Fearing the actions of a god-like Super Hero l...

# 4. Porządkowanie danych

In [6]:
# porządkowanie
# wypełnienie pustych wartości
df['overview'] = df['overview'].fillna('')

# zamiana jsona gatunków na string
def extract_genres(genre_str):
    try:
        genres = json.loads(genre_str)
        return " ".join([g['name'] for g in genres])
    except:
        return ""

df['genres_clean'] = df['genres'].apply(extract_genres) # utworzenie nowej kolumny z wypisanymi gatunkami

In [7]:
df['genres_clean'][0:10]

0    Action Adventure Fantasy Science Fiction
1                    Adventure Fantasy Action
2                      Action Adventure Crime
3                 Action Crime Drama Thriller
4            Action Adventure Science Fiction
5                    Fantasy Action Adventure
6                            Animation Family
7            Action Adventure Science Fiction
8                    Adventure Fantasy Family
9                    Action Adventure Fantasy
Name: genres_clean, dtype: object

In [8]:
# połączenie gatunków i opis fabuły
df['combined_text'] = df['genres_clean'] + " " + df['overview']

In [9]:
df[['combined_text', 'title']][0:10]

,combined_text,title
0,Action Adventure Fantasy Science Fiction In th...,Avatar
1,"Adventure Fantasy Action Captain Barbossa, lon...",Pirates of the Caribbean: At World's End
2,Action Adventure Crime A cryptic message from ...,Spectre
3,Action Crime Drama Thriller Following the deat...,The Dark Knight Rises
4,Action Adventure Science Fiction John Carter i...,John Carter
5,Fantasy Action Adventure The seemingly invinci...,Spider-Man 3
6,Animation Family When the kingdom's most wante...,Tangled
7,Action Adventure Science Fiction When Tony Sta...,Avengers: Age of Ultron
8,Adventure Fantasy Family As Harry begins his s...,Harry Potter and the Half-Blood Prince
9,Action Adventure Fantasy Fearing the actions o...,Batman v Superman: Dawn of Justice

# 5. Ładowanie modelu

In [10]:
# ładowanie modelu z huggingface transformers z użyciem pipeline
extractor = pipeline("feature-extraction", model="sentence-transformers/all-MiniLM-L6-v2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [11]:
print(f'{type(extractor.model)} {extractor.model.config.name_or_path}') # sprawdzenie załadowanego modelu
# class 'transformers.models.bert.modeling_bert.BertModel'> sentence-transformers/all-MiniLM-L6-v2

<class 'transformers.models.bert.modeling_bert.BertModel'> sentence-transformers/all-MiniLM-L6-v2

In [12]:
# test
test_text = ["A group of scientists travel through time."]
test_vector = extractor(test_text)

In [13]:
test_vector # podgląd testowego wektora

[[[[-0.12500961124897003,
    0.04684446007013321,
    0.28042536973953247,
    0.4146181344985962,
    0.08147222548723221,
    -0.10760804265737534,
    -0.19736722111701965,
    -0.039009612053632736,
    0.14230209589004517,
    -0.007588270585983992,
    0.03306703642010689,
    -0.1422772854566574,
    -0.5679792165756226,
    0.15602126717567444,
    -0.3776222765445709,
    -0.34333857893943787,
    -0.23028722405433655,
    -0.02858954668045044,
    0.22711153328418732,
    -0.17114491760730743,
    -0.3428175747394562,
    0.07367226481437683,
    0.1985018402338028,
    0.23038020730018616,
    -0.11654341965913773,
    0.17725713551044464,
    -0.2533400058746338,
    -0.24485383927822113,
    0.17419393360614777,
    -0.412802129983902,
    -0.3961118161678314,
    0.05478297173976898,
    -0.496651291847229,
    -0.012530950829386711,
    -0.2831517457962036,
    0.18048444390296936,
    -0.026384912431240082,
    -0.05455079302191734,
    0.26275065541267395,
    0.14970554411411285,
    0.14494851231575012,
    -0.037835653871297836,
    0.2737342417240143,
    0.46502822637557983,
    -0.0887492448091507,
    -0.09259416162967682,
    0.40814775228500366,
    -0.4444279372692108,
    -0.003802994731813669,
    0.3661917448043823,
    -0.35549983382225037,
    0.09405756741762161,
    -0.2911425232887268,
    -0.11687230318784714,
    0.20771321654319763,
    0.24244588613510132,
    0.2782313823699951,
    0.16701020300388336,
    -0.14327949285507202,
    -0.5635300278663635,
    0.1405133157968521,
    -0.42905887961387634,
    -0.5851662755012512,
    -0.13808423280715942,
    -0.08448220789432526,
    0.22306868433952332,
    -0.36174067854881287,
    0.0068435813300311565,
    0.1067083477973938,
    0.024794789031147957,
    0.2025962620973587,
    0.5265544056892395,
    0.033075813204050064,
    -0.27833133935928345,
    0.18713749945163727,
    0.0900895744562149,
    0.4475492537021637,
    0.09730353206396103,
    0.3303588330745697,
    0.07185305655002594,
    0.2834460437297821,
    -0.40613049268722534,
    -0.3551163971424103,
    -0.11519882827997208,
    -0.30576667189598083,
    -0.3327641785144806,
    0.01767546869814396,
    0.34772706031799316,
    0.026453273370862007,
    -0.2587130665779114,
    0.011507815681397915,
    0.02203715406358242,
    0.22744467854499817,
    -0.05170264095067978,
    -0.3367213010787964,
    0.25411882996559143,
    0.02004220522940159,
    0.16814155876636505,
    0.42883870005607605,
    5.570059776306152,
    -0.16371707618236542,
    0.10877680033445358,
    -0.20447611808776855,
    0.40401196479797363,
    -0.1029525175690651,
    -0.26444366574287415,
    -0.04036007449030876,
    -0.18879163265228271,
    0.24435487389564514,
    0.21306364238262177,
    0.24714542925357819,
    0.11226048320531845,
    -0.09204892814159393,
    0.2768554985523224,
    0.07920459657907486,
    -0.30698201060295105,
    -0.3713228106498718,
    0.39670783281326294,
    0.22392067313194275,
    0.08246771991252899,
    -0.2345617115497589,
    0.3938576877117157,
    0.08872058987617493,
    -0.19508454203605652,
    0.15578562021255493,
    -0.6884382367134094,
    0.29898273944854736,
    -5.195224236848988e-32,
    0.3164407014846802,
    0.14554095268249512,
    0.006858148146420717,
    0.038290612399578094,
    0.15787211060523987,
    0.3693344295024872,
    -0.5216225385665894,
    -0.006646105088293552,
    -0.09607554972171783,
    -0.31682172417640686,
    -0.27784740924835205,
    -0.24303781986236572,
    -0.0823594406247139,
    -0.31265246868133545,
    -0.1790943443775177,
    0.11207728832960129,
    0.008650745265185833,
    -0.03875396400690079,
    0.24092142283916473,
    -0.006221608258783817,
    0.1348601132631302,
    0.0734710767865181,
    -0.41849902272224426,
    -0.12930819392204285,
    0.4448809027671814,
    0.06616359204053879,
    -0.19227337837219238,
    0.138485386967659,
    -0.11817608028650284,
    -0.2839176654815674,
    -0.20125608146190643,
    0.2523987889289856,
    -0.6622288823127747,
    -0.16156624257564545,
    0.5009708404541016,
    -0.16787627339363098,
    -0.04534260928630829,
    0.07090207189321518,
    0.1473509520292282,
    -0.19658218324184418,
    0.1194547787308693,
    -0.012689933180809021,
    -0.275936484336853,
    -0.23205621540546417,
    0.10438955575227737,
    -0.0019888521637767553,
    0.23317813873291016,
    0.014657446183264256,
    -0.07415667921304703,
    0.5703830122947693,
    -0.21180827915668488,
    -0.09082338958978653,
    0.019778020679950714,
    -0.5982378125190735,
    0.19648845493793488,
    -0.1970084309577942,
    0.12692803144454956,
    0.044581133872270584,
    0.010121924802660942,
    0.27356261014938354,
    0.5124040246009827,
    0.08796267956495285,
    0.17344948649406433,
    0.061418287456035614,
    0.17657223343849182,
    0.1227525845170021,
    -0.21609489619731903,
    0.23078563809394836,
    0.4578417241573334,
    0.377461701631546,
    -0.07211601734161377,
    -0.1871662437915802,
    -0.06877637654542923,
    -0.0606321282684803,
    0.1131591945886612,
    0.17811474204063416,
    0.20755985379219055,
    -0.021860171109437943,
    0.034767456352710724,
    0.17082077264785767,
    -0.0431504063308239,
    -0.6441335678100586,
    0.35882067680358887,
    -0.18907323479652405,
    0.08710392564535141,
    -0.004779611248522997,
    -0.11741175502538681,
    0.2443232536315918,
    -0.002415421651676297,
    -0.45814138650894165,
    0.12193887680768967,
    0.015244564972817898,
    0.5946283340454102,
    -0.1769377738237381,
    -0.5513079166412354,
    3.959531350953153e-32,
    -0.017583908513188362,
    -0.08647088706493378,
    -0.1314750462770462,
    -0.008934570476412773,
    0.24009622633457184,
    0.00855737179517746,
    -0.4441453516483307,
    0.0004713742819149047,
    -0.03695940971374512,
    0.32526683807373047,
    0.2679598331451416,
    -0.24318474531173706,
    -0.44006669521331787,
    -0.6505142450332642,
    0.20314843952655792,
    -0.2512742578983307,
    0.07420287281274796,
    -0.39958110451698303,
    -0.34906309843063354,
    0.10676337778568268,
    -0.02377370186150074,
    -0.2940804958343506,
    -0.013454800471663475,
    -0.17768236994743347,
    0.44956010580062866,
    0.11686868965625763,
    0.43983468413352966,
    0.0457342267036438,
    -0.06868729740381241,
    0.10783153772354126,
    -0.4094518721103668,
    -0.15376639366149902,
    -0.05327925086021423,
    0.012612665072083473,
    -0.14735136926174164,
    0.26709243655204773,
    0.31779035925865173,
    -0.03336126357316971,
    -0.07197974622249603,
    -0.09376759827136993,
    -0.03722865879535675,
    0.48356977105140686,
    -0.10273002088069916,
    0.01804906688630581,
    -0.12146392464637756,
    0.30419832468032837,
    -0.14062434434890747,
    0.48295697569847107,
    -0.19896501302719116,
    0.4119298756122589,
    0.10550551861524582,
    -0.006928706541657448,
    0.13210690021514893,
    -0.46530067920684814,
    -0.03737533465027809,
    0.13525080680847168,
    0.1922140270471573,
    -0.022485679015517235,
    -0.13615049421787262,
    0.35995587706565857,
    -0.1855146586894989,
    -0.5193145275115967,
    0.12400922179222107,
    0.1950567662715912,
    -0.552592933177948,
    -0.4085315465927124,
    -0.22708718478679657,
    0.05754179507493973,
    -0.21722038090229034,
    0.03544297814369202,
    0.37556636333465576,
    0.15044628083705902,
    -0.3640497326850891,
    0.22857563197612762,
    0.15499946475028992,
    0.1316927820444107,
    0.010068750940263271,
    0.36213022470474243,
    0.014837919734418392,
    0.13975867629051208,
    0.022482875734567642,
    0.1952916979789734,
    0.30358773469924927,
    0.211319699883461,
    -0.12044624239206314,
    -0.10100150108337402,
    -0.3393182158470154,
    -0.06089290603995323,
    -0.08128637820482254,
    0.08739234507083893,
    -0.07222265750169754,
    -0.14193497598171234,
    0.049188993871212006,
    0.23995524644851685,
    0.013128421269357204,
    -8.950623708869898e-08,
    0.26486414670944214,
    0.1185879334807396,
    -0.012428651563823223,
    -0.06185591593384743,
    -0.10490818321704865,
    -0.20538204908370972,
    -0.025294743478298187,
    0.011350227519869804,
    0.36727526783943176,
    0.12186255306005478,
    0.3438475728034973,
    -0.13225990533828735,
    0.21558038890361786,
    0.3055744469165802,
    0.016142088919878006,
    -0.029998529702425003,
    -0.14365312457084656,
    -0.5422642827033997,
    0.050030846148729324,
    0.13383610546588898,
    -0.24269670248031616,
    0.2066611647605896,
    0.34248432517051697,
    -0.2935533821582794,
    0.24436546862125397,
    0.25083407759666443,
    -0.0572042241692543,
    -0.42014285922050476,
    0.35071080923080444,
    -0.044175174087285995,
    -0.2966665029525757,
    0.08674520999193192,
    -0.7259222865104675,
    0.050817765295505524,
    -0.3835519850254059,
    -0.6783220767974854,
    0.07049299031496048,
    0.1334652602672577,
    -0.25985977053642273,
    0.5078985691070557,
    -0.08614319562911987,
    -0.017584560438990593,
    -0.3057419955730438,
    0.07017169147729874,
    -0.37830182909965515,
    -0.28963354229927063,
    0.07382707297801971,
    -0.24018456041812897,
    -0.30196306109428406,
    0.06431548297405243,
    0.2528381943702698,
    0.20003075897693634,
    -0.10842672735452652,
    -0.12142230570316315,
    -0.12334300577640533,
    0.5321479439735413,
    -0.329084187746048,
    -0.049368083477020264,
    -0.6964950561523438,
    -0.21485094726085663,
    0.13076527416706085,
    -0.14165189862251282,
    -0.3891945481300354,
    -0.27933061122894287],
   [-0.2623057961463928,
    -0.22032740712165833,
    -0.18006396293640137,
    0.5316143035888672,
    -0.026802783831954002,
    -0.3985537588596344,
    -0.20020310580730438,
    -0.17251244187355042,
    0.4420645833015442,
    0.27424368262290955,
    0.19676099717617035,
    -0.2576853036880493,
    -0.390162855386734,
    0.3038966953754425,
    -0.871492862701416,
    0.05173151567578316,
    -0.5279451608657837,
    -0.27470844984054565,
    0.23281800746917725,
    -0.40237244963645935,
    -0.817022979259491,
    0.0979938730597496,
    0.17503660917282104,
    0.4734364449977875,
    -0.029333418235182762,
    0.32145997881889343,
    -0.17128854990005493,
    -0.24128605425357819,
    0.02732245810329914,
    0.2504962682723999,
    -0.15014849603176117,
    0.24745815992355347,
    0.09204374253749847,
    0.1909007579088211,
    -0.16866770386695862,
    0.24282698333263397,
    0.05463413894176483,
    0.16404961049556732,
    0.10831442475318909,
    0.3519389033317566,
    0.15764157474040985,
    -0.04505074769258499,
    0.1710289716720581,
    0.30204054713249207,
    -0.10532394796609879,
    -0.14807777106761932,
    0.22149918973445892,
    -0.19208183884620667,
    0.009545630775392056,
    0.45490047335624695,
    -0.24843454360961914,
    -0.6396411657333374,
    -0.20779740810394287,
    -0.06930220127105713,
    0.06535332649946213,
    0.09057106077671051,
    0.27511540055274963,
    -0.11639836430549622,
    -0.05576159060001373,
    -0.4387683868408203,
    0.44594842195510864,
    -0.29392969608306885,
    -0.11330927163362503,
    0.2594138979911804,
    0.20116382837295532,
    0.3956570327281952,
    -0.0907474160194397,
    0.16205187141895294,
    0.27729395031929016,
    -0.5157366394996643,
    0.4180951714515686,
    0.47579291462898254,
    -9.546261571813375e-05,
    0.07037007808685303,
    0.2856558859348297,
    0.14111648499965668,
    0.19849129021167755,
    0.0313003808259964,
    0.2790181040763855,
    -0.14695829153060913,
    0.37879249453544617,
    -0.4773983657360077,
    -0.457476943731308,
    -0.0038290091324597597,
    -0.07178837805986404,
    -0.1994737833738327,
    -0.15247242152690887,
    0.3222537636756897,
    -0.17003537714481354,
    -0.2467166632413864,
    -0.21035660803318024,
    -0.003011643886566162,
    0.25446203351020813,
    -0.13366195559501648,
    -0.19878804683685303,
    0.10331717878580093,
    0.22677142918109894,
    -0.07479004561901093,
    0.6644389629364014,
    -0.4258350133895874,
    -0.07876553386449814,
    -0.10991032421588898,
    0.1954977810382843,
    0.3540119528770447,
    -0.1709970384836197,
    -0.5718493461608887,
    0.08676227927207947,
    -0.35277581214904785,
    0.5096467733383179,
    0.04203350096940994,
    0.051649127155542374,
    0.18976666033267975,
    -0.4727849066257477,
    0.33522865176200867,
    0.04117502272129059,
    -0.4051705598831177,
    -0.34064412117004395,
    0.5681614875793457,
    0.07127204537391663,
    0.06997887045145035,
    -0.1439075618982315,
    0.34214913845062256,
    0.14274610579013824,
    -0.5011475682258606,
    0.44247955083847046,
    0.48075324296951294,
    -0.2399987280368805,
    -9.354381858815423e-32,
    0.27179092168807983,
    0.24558232724666595,
    -0.22597333788871765,
    0.2421637326478958,
    0.3068055510520935,
    0.12212245166301727,
    -0.35840991139411926,
    -0.1580553948879242,
    -0.27563905715942383,
    -0.20462633669376373,
    -0.5273207426071167,
    0.010365832597017288,
    0.203717440366745,
    0.28169533610343933,
    -0.0076415943913161755,
    -0.29198792576789856,
    -0.18615558743476868,
    0.07476527988910675,
    -0.10945964604616165,
    0.04933959245681763,
    -0.4051492214202881,
    0.5448032021522522,
    -0.3324480354785919,
    -0.3379635214805603,
    0.20405825972557068,
    -0.09146151691675186,
    -0.3769367039203644,
    0.07854699343442917,
    0.11782751977443695,
    0.06635227054357529,
    0.154804989695549,
    0.014603497460484505,
    -0.3325570821762085,
    -0.040565915405750275,
    0.16196005046367645,
    -0.36482012271881104,
    0.17744915187358856,
    -0.25873681902885437,
    0.7169389724731445,
    -0.07244838029146194,
    0.08338463306427002,
    -0.19040054082870483,
    -0.03828880190849304,
    -0.173448845744133,
    0.08793570846319199,
    0.24051065742969513,
    0.2656114101409912,
    -0.007438083179295063,
    0.0975353866815567,
    0.5134410262107849,
    -0.4246061146259308,
    -0.0864277109503746,
    -0.1917189210653305,
    -0.4504868984222412,
    0.2799829840660095,
    -0.07382037490606308,
    -0.10226352512836456,
    0.28529617190361023,
    -0.05881795287132263,
    -0.038256533443927765,
    0.5199450254440308,
    0.3920517563819885,
    -0.35296621918678284,
    0.29630300402641296,
    0.5943750143051147,
    0.21355898678302765,
    -0.09383992105722427,
    0.1245172917842865,
    0.7052983641624451,
    0.38953322172164917,
    -0.2778892517089844,
    -0.07825911790132523,
    0.06649668514728546,
    -0.17881004512310028,
    -0.10390367358922958,
    0.2627587616443634,
    -0.05442168191075325,
    0.08889829367399216,
    -0.159413680434227,
    0.1852719783782959,
    -0.22925524413585663,
    -0.6155107617378235,
    0.2702501714229584,
    -0.5950354933738708,
    -0.2432350367307663,
    0.007695937529206276,
    -0.2671513855457306,
    0.1292921006679535,
    -0.15474708378314972,
    -0.30267372727394104,
    -0.1899005025625229,
    0.12613210082054138,
    0.3804498612880707,
    -0.0008507536840625107,
    -0.19996775686740875,
    6.274057687203159e-32,
    0.02220180630683899,
    -0.004526004660874605,
    -0.16813941299915314,
    0.11740349233150482,
    0.6599136590957642,
    0.15085139870643616,
    -0.38951215147972107,
    0.09631945937871933,
    -0.16553480923175812,
    0.2595953941345215,
    0.10654085874557495,
    -0.1652199774980545,
    -0.014976299367845058,
    -0.4788857400417328,
    0.26519227027893066,
    -0.1767309010028839,
    0.0541972890496254,
    -0.3709613084793091,
    -0.19436365365982056,
    0.22304919362068176,
    -0.04216400533914566,
    -0.1553969830274582,
    -0.017825894057750702,
    -0.006565597373992205,
    0.3372093141078949,
    0.23368285596370697,
    0.7567184567451477,
    -0.07198184728622437,
    -0.36591020226478577,
    0.03923941031098366,
    -0.5318781137466431,
    -0.18483108282089233,
    0.23665417730808258,
    0.020718442276120186,
    -0.07544028013944626,
    0.4122721254825592,
    0.4803987443447113,
    -0.049148980528116226,
    -0.2702241539955139,
    -0.13086874783039093,
    -0.07015115022659302,
    0.6706658005714417,
    -0.07999389618635178,
    0.34754642844200134,
    -0.1231948509812355,
    0.09768353402614594,
    -0.030255576595664024,
    0.4439564645290375,
    -0.05245945602655411,
    0.2613820433616638,
    -0.013931255787611008,
    -0.20709897577762604,
    0.20361599326133728,
    -0.40079447627067566,
    0.11139249056577682,
    0.21410928666591644,
    -0.16235916316509247,
    0.0970093309879303,
    -0.0780995711684227,
    0.5557090640068054,
    -0.07575267553329468,
    -0.4514838457107544,
    0.25249338150024414,
    0.6472939848899841,
    -0.723130464553833,
    -0.4052162766456604,
    -0.10111971199512482,
    0.187771275639534,
    -0.21128511428833008,
    0.08883325010538101,
    0.6149659752845764,
    -0.035339053720235825,
    -0.05544496700167656,
    -0.2132365107536316,
    0.20006109774112701,
    0.2026159167289734,
    -0.1629580855369568,
    -0.1681894212961197,
    0.07328318059444427,
    -0.019673986360430717,
    -0.13628213107585907,
    0.10863026976585388,
    0.4575217366218567,
    0.42691776156425476,
    -0.08761235326528549,
    -0.16597837209701538,
    -0.012737428769469261,
    -0.02122645452618599,
    -0.019129252061247826,
    0.18873833119869232,
    0.1220836490392685,
    -0.2944926917552948,
    -0.10024230927228928,
    0.01662713848054409,
    -0.03815055266022682,
    -9.180106985695602e-08,
    0.5462508201599121,
    -0.10071638971567154,
    -0.02546699158847332,
    -0.15299901366233826,
    -0.036572206765413284,
    -0.3632238209247589,
    -0.15192489326000214,
    0.24399864673614502,
    0.22161588072776794,
    0.10479056090116501,
    0.16699500381946564,
    0.016130821779370308,
    0.020896723493933678,
    0.6220196485519409,
    -0.11583615094423294,
    0.07357609272003174,
    -0.27785226702690125,
    -0.2825965881347656,
    -0.1229342594742775,
    0.09656597673892975,
    0.06091621518135071,
    0.1958802491426468,
    0.4378194510936737,
    -0.2289416342973709,
    0.16701626777648926,
    0.227285236120224,
    -0.3114677965641022,
    -0.18219779431819916,
    0.10639596730470657,
    0.13139158487319946,
    -0.44737765192985535,
    0.4021311104297638,
    -0.6808642148971558,
    0.13456150889396667,
    -0.26923486590385437,
    -0.4548889696598053,
    -0.2390107959508896,
    0.042389605194330215,
    -0.018290812149643898,
    0.4265972375869751,
    -0.10332851856946945,
    0.30314308404922485,
    -0.3924225866794586,
    0.3942868709564209,
    -0.008666816167533398,
    -0.4787112772464752,
    0.052930619567632675,
    -0.1887335181236267,
    -0.07871417701244354,
    -0.035649098455905914,
    0.3821289837360382,
    0.12948469817638397,
    0.03362825885415077,
    0.1378423273563385,
    -0.4101470708847046,
    0.27086421847343445,
    -0.32105568051338196,
    0.13952046632766724,
    -0.657966673374176,
    -0.13214635848999023,
    0.23033587634563446,
    -0.18521052598953247,
    -0.1164582371711731,
    0.13546720147132874],
   [0.34415867924690247,
    -1.077437162399292,
    0.17775632441043854,
    0.28681325912475586,
    -0.3541529178619385,
    -0.4466036558151245,
    0.09467384219169617,
    -0.6686768531799316,
    0.7420403361320496,
    0.3220379948616028,
    0.4189453721046448,
    0.1022527813911438,
    -0.44432589411735535,
    -0.23424437642097473,
    -0.45641252398490906,
    -0.2850772738456726,
    -0.8609788417816162,
    -0.625058650970459,
    -0.8745434284210205,
    -1.0097209215164185,
    -1.3724255561828613,
    -0.3580332398414612,
    -0.01986049674451351,

In [14]:
print(f"Wymiar wektora: {np.array(test_vector).shape}")
# (1, 1, 10, 384) - 1 przekazane zdanie, 1 warstwa, 10 tokenów, 384 wymiarów

Wymiar wektora: (1, 1, 10, 384)

# 6. Tokenizowanie

In [15]:
# funkcja kodująca
def get_sentence_embedding(text_list):
    features = extractor(text_list, truncation=True) # wektory

    embeddings = []

    for movie_tokens in features:
      movie_vector = np.mean(movie_tokens, axis=1)
      embeddings.append(movie_vector)

    return np.array(embeddings)

In [16]:
%%time
# %%time - pomiar czasu

# kodowanie opisów na wektory (40s)
# co 500 filmów informacja o trwającym przetwarzaniu
# GPU:
# CPU times: user 38.9 s, sys: 1.46 s, total: 40.4 s
# Wall time: 40.6 s


batch_size = 500
all_embeddings = []

for i in range(0, len(df), batch_size):
    batch_texts = df['combined_text'].iloc[i:i+batch_size].tolist()
    batch_emb = get_sentence_embedding(batch_texts)
    all_embeddings.append(batch_emb)
    print(f"{i//batch_size + 1}/{len(df)//batch_size + 1}")

# tabela z zakodowanymi filmami
movie_embeddings = np.vstack(all_embeddings)
movie_embeddings = movie_embeddings.squeeze(axis=1)

1/10
2/10
3/10
4/10
5/10
6/10
7/10
8/10

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

9/10
10/10
CPU times: user 39.3 s, sys: 1.45 s, total: 40.8 s
Wall time: 41 s

In [17]:
# zapisanie tokenów:
# np.save('movie_embeddings.npy', movie_embeddings)
# link do githuba:
# https://github.com/AleksanderGlegola/DataScienceProject/raw/refs/heads/main/movie_embeddings.npy

In [18]:
print(movie_embeddings.shape) # rozmiar
movie_embeddings[0:10]

(4803, 384)

array([[ 0.01046226,  0.10285392,  0.07232867, ..., -0.06489653,
        -0.11245102, -0.01052745],
       [-0.10193018, -0.15163373, -0.24282401, ..., -0.40726754,
        -0.2027139 , -0.04137015],
       [-0.18795561,  0.10316822, -0.06672248, ..., -0.12702616,
        -0.09362258, -0.14538914],
       ...,
       [-0.04654187, -0.02167249,  0.01644424, ..., -0.23778178,
        -0.26724738, -0.05181176],
       [-0.1056946 ,  0.07714529,  0.04477665, ...,  0.06030496,
        -0.07040969,  0.06834619],
       [ 0.08123052,  0.03557537, -0.15810834, ..., -0.11205386,
        -0.06775663,  0.11388425]])

# 6. Rekomendowanie

In [19]:
def recommend_movies(user_plot, top_n=5, list_only=False):
    # wektoryzowanie podanego opisu
    user_embedding = get_sentence_embedding([user_plot])
    user_embedding = user_embedding.squeeze(axis=1)

    # obliczanie podobieństwa dla wszystkich filmów
    # wartości <-1,1> (1 - idealne dopasowanie)
    similarities = cosine_similarity(user_embedding, movie_embeddings)

    # sortowanie (ostatnie elementy , bo argsort sortuje rosnąco)
    similar_indices = similarities[0].argsort()[-top_n:][::-1]

    # wyniki
    print(f"\nPodany opis: '{user_plot}'\n")
    for i in similar_indices:
        score = similarities[0][i]
        title = df.iloc[i]['title']
        if not list_only:
          if len(df.iloc[i]['overview'])>200:
            overview = df.iloc[i]['overview'][:200] + "..." # ucięcie tekstu
          else:
            overview = df.iloc[i]['overview'][:-1]
          print(f"Tytuł: {title} (Podobieństwo: {score:.2f})")
          print(f"Opis:  {overview}\n")
        else:
          print(f"Tytuł: {title} (Podobieństwo: {score:.2f})")

In [20]:
# test
recommend_movies("A group of scientists travel through time to prevent a disaster.")

Podany opis: 'A group of scientists travel through time to prevent a disaster.'

Tytuł: Left Behind (Podobieństwo: 0.51)
Opis:  A small group of survivors are left behind after millions of people suddenly vanish during the rapture and the world is plunged into chaos and destruction

Tytuł: Mutant World (Podobieństwo: 0.50)
Opis:  A decade after a disastrous meteor impact wipes out most of society, a group of survivalists emerge to find themselves on a twisted version of the old Earth, with a nascent society besieged by vicious...

Tytuł: Project Almanac (Podobieństwo: 0.49)
Opis:  A group of teens discover secret plans of a time machine, and construct one. However, things start to get out of control

Tytuł: Prometheus (Podobieństwo: 0.47)
Opis:  A team of explorers discover a clue to the origins of mankind on Earth, leading them on a journey to the darkest corners of the universe. There, they must fight a terrifying battle to save the future ...

Tytuł: Timecrimes (Podobieństwo: 0.46)
Opis:  A man accidentally gets into a time machine and travels back in time nearly an hour. Finding himself will be the first of a series of disasters of unforeseeable consequences

In [21]:
recommend_movies("A group of scientists travel through time to prevent a disaster.", top_n=20, list_only=True)

Podany opis: 'A group of scientists travel through time to prevent a disaster.'

Tytuł: Left Behind (Podobieństwo: 0.51)
Tytuł: Mutant World (Podobieństwo: 0.50)
Tytuł: Project Almanac (Podobieństwo: 0.49)
Tytuł: Prometheus (Podobieństwo: 0.47)
Tytuł: Timecrimes (Podobieństwo: 0.46)
Tytuł: The Divide (Podobieństwo: 0.45)
Tytuł: Fantastic Four (Podobieństwo: 0.44)
Tytuł: About Time (Podobieństwo: 0.42)
Tytuł: In Time (Podobieństwo: 0.42)
Tytuł: Knowing (Podobieństwo: 0.42)
Tytuł: Interstellar (Podobieństwo: 0.42)
Tytuł: Skyline (Podobieństwo: 0.41)
Tytuł: Event Horizon (Podobieństwo: 0.41)
Tytuł: Dawn of the Planet of the Apes (Podobieństwo: 0.40)
Tytuł: Time Changer (Podobieństwo: 0.40)
Tytuł: Tomorrowland (Podobieństwo: 0.40)
Tytuł: Sunshine (Podobieństwo: 0.39)
Tytuł: Mission to Mars (Podobieństwo: 0.39)
Tytuł: Hot Tub Time Machine (Podobieństwo: 0.39)
Tytuł: Lost in Space (Podobieństwo: 0.38)

# 7. Testowanie

In [22]:
# testowanie rekomendowania kolejnych filmów z serii
# Harry Potter
user_plot = 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. \
He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard \
Lord Voldemort, who seeks to conquer the magical world and murdered Harry\'s parents when Harry was a baby.'
recommend_movies(user_plot)

Podany opis: 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard Lord Voldemort, who seeks to conquer the magical world and murdered Harry's parents when Harry was a baby.'

Tytuł: Harry Potter and the Philosopher's Stone (Podobieństwo: 0.66)
Opis:  Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School ...

Tytuł: Harry Potter and the Goblet of Fire (Podobieństwo: 0.64)
Opis:  Harry starts his fourth year at Hogwarts, competes in the treacherous Triwizard Tournament and faces the evil Lord Voldemort. Ron and Hermione help Harry manage the pressure – but Voldemort lurks, awa...

Tytuł: Harry Potter and the Prisoner of Azkaban (Podobieństwo: 0.59)
Opis:  Harry, Ron and Hermione return to Hogwarts for another magic-filled year. Harry comes face to face with danger yet again, this time in the form of escaped convict, Sirius Black – and turns to sympathe...

Tytuł: Harry Potter and the Chamber of Secrets (Podobieństwo: 0.59)
Opis:  Ignoring threats to his life, Harry returns to Hogwarts to investigate – aided by Ron and Hermione – a mysterious series of attacks

Tytuł: Harry Potter and the Half-Blood Prince (Podobieństwo: 0.55)
Opis:  As Harry begins his sixth year at Hogwarts, he discovers an old book marked as 'Property of the Half-Blood Prince', and begins to learn more about Lord Voldemort's dark past

In [23]:
recommend_movies(user_plot, top_n=20, list_only=True)

Podany opis: 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard Lord Voldemort, who seeks to conquer the magical world and murdered Harry's parents when Harry was a baby.'

Tytuł: Harry Potter and the Philosopher's Stone (Podobieństwo: 0.66)
Tytuł: Harry Potter and the Goblet of Fire (Podobieństwo: 0.64)
Tytuł: Harry Potter and the Prisoner of Azkaban (Podobieństwo: 0.59)
Tytuł: Harry Potter and the Chamber of Secrets (Podobieństwo: 0.59)
Tytuł: Harry Potter and the Half-Blood Prince (Podobieństwo: 0.55)
Tytuł: Harry Potter and the Order of the Phoenix (Podobieństwo: 0.53)
Tytuł: Pan's Labyrinth (Podobieństwo: 0.45)
Tytuł: Disturbia (Podobieństwo: 0.44)
Tytuł: Dude Where's My Dog? (Podobieństwo: 0.43)
Tytuł: The Exorcist (Podobieństwo: 0.43)
Tytuł: Bogus (Podobieństwo: 0.42)
Tytuł: Something's Gotta Give (Podobieństwo: 0.41)
Tytuł: St. Vincent (Podobieństwo: 0.41)
Tytuł: Little Boy (Podobieństwo: 0.41)
Tytuł: Heli (Podobieństwo: 0.41)
Tytuł: A Room for Romeo Brass (Podobieństwo: 0.41)
Tytuł: The Indian in the Cupboard (Podobieństwo: 0.40)
Tytuł: Martian Child (Podobieństwo: 0.40)
Tytuł: Boyhood (Podobieństwo: 0.40)
Tytuł: Wish I Was Here (Podobieństwo: 0.40)

In [24]:
# Lord of the rings
user_plot = 'The Hobbit Frodo Baggins inherits the One Ring, an artifact of \
immense power created by the Dark Lord Sauron. To save Middle-earth, Frodo and \
eight companions—the Fellowship—embark on a perilous quest to Mount Doom in \
Mordor, the only place where the Ring can be destroyed'
recommend_movies(user_plot)

Podany opis: 'The Hobbit Frodo Baggins inherits the One Ring, an artifact of immense power created by the Dark Lord Sauron. To save Middle-earth, Frodo and eight companions—the Fellowship—embark on a perilous quest to Mount Doom in Mordor, the only place where the Ring can be destroyed'

Tytuł: The Lord of the Rings: The Fellowship of the Ring (Podobieństwo: 0.88)
Opis:  Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowshi...

Tytuł: The Lord of the Rings: The Return of the King (Podobieństwo: 0.59)
Opis:  Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam bring the ring...

Tytuł: The Lord of the Rings: The Two Towers (Podobieństwo: 0.56)
Opis:  Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fell...

Tytuł: The Hobbit: An Unexpected Journey (Podobieństwo: 0.55)
Opis:  Bilbo Baggins, a hobbit enjoying his quiet life, is swept into an epic quest by Gandalf the Grey and thirteen dwarves who seek to reclaim their mountain home from Smaug, the dragon

Tytuł: The Hobbit: The Desolation of Smaug (Podobieństwo: 0.51)
Opis:  The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to get their gold back from the Dragon, Smaug

In [25]:
# James Bond
user_plot = 'James Bond travels to Jamaica to investigate the murder of a \
British agent. He discovers that a megalomaniacal scientist named Dr. No, \
a member of the criminal organization SPECTRE, is using a secret atomic reactor \
on the island of Crab Key to sabotage American space rocket launches'
recommend_movies(user_plot)

Podany opis: 'James Bond travels to Jamaica to investigate the murder of a British agent. He discovers that a megalomaniacal scientist named Dr. No, a member of the criminal organization SPECTRE, is using a secret atomic reactor on the island of Crab Key to sabotage American space rocket launches'

Tytuł: Dr. No (Podobieństwo: 0.74)
Opis:  In the film that launched the James Bond saga, Agent 007 battles mysterious Dr. No, a scientific genius bent on destroying the U.S. space program. As the countdown to disaster begins, Bond must go to ...

Tytuł: Octopussy (Podobieństwo: 0.67)
Opis:  James Bond is sent to investigate after a fellow “00” agent is found dead with a priceless Farberge egg. James bond follows the mystery and uncovers a smuggling scandal and a Russian General who wants...

Tytuł: Live and Let Die (Podobieństwo: 0.64)
Opis:  James Bond must investigate a mysterious murder case of a British agent in New Orleans. Soon he finds himself up against a gangster boss named Mr. Big

Tytuł: The Living Daylights (Podobieństwo: 0.63)
Opis:  James Bond helps a Russian General escape into the west. He soon finds out that the KGB wants to kill him for helping the General. A little while later the General is kidnapped from the Secret Service...

Tytuł: Quantum of Solace (Podobieństwo: 0.57)
Opis:  Quantum of Solace continues the adventures of James Bond after Casino Royale. Betrayed by Vesper, the woman he loved, 007 fights the urge to make his latest mission personal. Pursuing his determinatio...

In [26]:
# filmy Marvela
# Iron Man
user_plot = 'Billionaire industrialist Tony Stark is kidnapped by terrorists and \
forced to build a weapon. Instead, he creates a high-tech armored suit to escape. \
Returning home, Stark shuts down his weapons manufacturing and perfects the armor \
to fight global corruption, ultimately taking down his greedy business partner'
recommend_movies(user_plot)

Podany opis: 'Billionaire industrialist Tony Stark is kidnapped by terrorists and forced to build a weapon. Instead, he creates a high-tech armored suit to escape. Returning home, Stark shuts down his weapons manufacturing and perfects the armor to fight global corruption, ultimately taking down his greedy business partner'

Tytuł: Iron Man (Podobieństwo: 0.72)
Opis:  After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil

Tytuł: Iron Man 2 (Podobieństwo: 0.64)
Opis:  With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with t...

Tytuł: Lords of London (Podobieństwo: 0.54)
Opis:  Tony is a notorious gangster with a big problem. He has woken up in an abandoned farmhouse, with blood on his shirt, and no memory of how he got there. He stumbles into a small town and discovers he’s...

Tytuł: Iron Man 3 (Podobieństwo: 0.52)
Opis:  When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution

Tytuł: Avengers: Age of Ultron (Podobieństwo: 0.51)
Opis:  When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villa...

# 8. Generowanie trójek

In [27]:
# założenie: filmy z tego samego gatunku są bardziej podobne niż filmy z innego gatunku
# tworzę trójki:
# - opis filmu (kotwica)
# - losowy film z tymi samymi gatunkami
# - losowy film z innymi gatunkami

In [28]:
# przykladowe filmy o podobnych gatunkach
df[['title', 'genres_clean', 'combined_text']][:200].sort_values(by='genres_clean')[:20]

,title,genres_clean,combined_text
44,Furious 7,Action,Action Deckard Shaw seeks revenge against Domi...
162,Stealth,Action,Action Deeply ensconced in a top-secret milita...
62,The Legend of Tarzan,Action Adventure,"Action Adventure Tarzan, having acclimated to ..."
21,Robin Hood,Action Adventure,Action Adventure When soldier Robin happens up...
152,Kung Fu Panda 3,Action Adventure Animation Comedy Family,Action Adventure Animation Comedy Family Conti...
187,Puss in Boots,Action Adventure Animation Family Fantasy,Action Adventure Animation Family Fantasy Long...
164,Lethal Weapon 4,Action Adventure Comedy Crime Thriller,Action Adventure Comedy Crime Thriller In the ...
167,Sahara,Action Adventure Comedy Drama Mystery,Action Adventure Comedy Drama Mystery Scouring...
150,Men in Black II,Action Adventure Comedy Science Fiction,Action Adventure Comedy Science Fiction Kay an...
70,Wild Wild West,Action Adventure Comedy Science Fiction Western,Action Adventure Comedy Science Fiction Wester...
2,Spectre,Action Adventure Crime,Action Adventure Crime A cryptic message from ...
72,Suicide Squad,Action Adventure Crime Fantasy Science Fiction,Action Adventure Crime Fantasy Science Fiction...
97,Shin Godzilla,Action Adventure Drama Horror Science Fiction,Action Adventure Drama Horror Science Fiction ...
138,The Last Airbender,Action Adventure Family Fantasy,Action Adventure Family Fantasy The story foll...
126,Thor: The Dark World,Action Adventure Fantasy,Action Adventure Fantasy Thor fights to restor...
30,Spider-Man 2,Action Adventure Fantasy,Action Adventure Fantasy Peter Parker is going...
19,The Hobbit: The Battle of the Five Armies,Action Adventure Fantasy,Action Adventure Fantasy Immediately after the...
9,Batman v Superman: Dawn of Justice,Action Adventure Fantasy,Action Adventure Fantasy Fearing the actions o...
107,Warcraft,Action Adventure Fantasy,Action Adventure Fantasy The peaceful realm of...
38,The Amazing Spider-Man 2,Action Adventure Fantasy,"Action Adventure Fantasy For Peter Parker, lif..."

In [29]:
# ziarno losowości
random.seed(42)

In [30]:
# kolumna z listą gatunków
df['genre_list'] = df['genres_clean'].apply(lambda x: x.split() if pd.notna(x) else [])

In [31]:
triplets = []

In [32]:
# funkcja generująca trójki dla każdego filmu
def generate_triplets():
  for idx, row in df.iterrows():
      anchor_text = row['combined_text']    # opis fabuły
      anchor_genres = row['genre_list']     # lista gatunków

      if not anchor_genres:                 # pusta lista gatunków
          continue

      # pozytywne przykłady (min. 1 gatunek taki sam)
      pos_mask = df['genre_list'].apply(lambda other_genres: any(g in other_genres for g in anchor_genres))
      pos_mask[idx] = False         # omijamy aktualnie sprawdzany film
      pos_movies = df[pos_mask]     # df z podobnymi filmami

      if pos_movies.empty:          # nie ma podobnych filmów
          continue

      # negatywne przykłady (nie ma nawet 1 wspólnego gatunku)
      neg_mask = df['genre_list'].apply(lambda other_genres: not any(g in other_genres for g in anchor_genres))
      neg_movies = df[neg_mask]

      if neg_movies.empty:        # nie ma nie podobnych filmów
          continue

      # losowa próbka pozytywna i negatywna
      pos_row = pos_movies.sample(n=1).iloc[0]
      neg_row = neg_movies.sample(n=1).iloc[0]

      # dodawanie trójki do listy trójek
      triplets.append({
          'anchor': anchor_text,                  # oryginalny tekst
          'positive': pos_row['combined_text'],   # tekst filmu podobnego
          'negative': neg_row['combined_text']    # tekst filmu nie podobnego
      })

In [33]:
# %%time
# czas generowania trójek (1min)
# CPU times: user 55.1 s, sys: 47.6 ms, total: 55.1 s
# Wall time: 55.4 s
generate_triplets()

CPU times: user 58.9 s, sys: 65.8 ms, total: 59 s
Wall time: 1min 4s

In [34]:
triplets[:2]

[{'anchor': 'Action Adventure Fantasy Science Fiction In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
  'positive': 'Action Adventure Fantasy The peaceful realm of Azeroth stands on the brink of war as its civilization faces a fearsome race of invaders: orc warriors fleeing their dying home to colonize another. As a portal opens to connect the two worlds, one army faces destruction and the other faces extinction. From opposing sides, two heroes are set on a collision course that will decide the fate of their family, their people, and their home.',
  'negative': "Comedy Drama Romance Jerry Maguire used to be a typical sports agent: willing to do just about anything he could to get the biggest possible contracts for his clients, plus a nice commission for himself. Then, one day, he suddenly has second thoughts about what he's really doing. When he voices these doubts, he ends up losing his job and all of his clients, save Rod Tidwell, an egomaniacal football player."},
 {'anchor': 'Adventure Fantasy Action Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.',
  'positive': 'Action Adventure Animation Comedy Family Rocky and Bullwinkle have been living off the finances made from the reruns of their cartoon show. Boris and Natasha somehow manage to crossover into reality and team up with Fearless Leader, an evil criminal turned media mogul with some evil plans up his sleeve. Rocky and Bullwinkle must stop the three of them before they wreak havoc.',
  'negative': 'Horror Comedy A once-famous painter rediscovers inspiration when he befriends a sleepwalking cannibal.'}]

# 9. Finetuning

In [35]:
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader

/tmp/ipykernel_3512/1305460641.py:1: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer, InputExample, losses

In [36]:
# wczytanie modelu
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [37]:
# przygotowanie danych do trenowania
train_examples = []
for trip in triplets:
    train_examples.append(InputExample(texts=[trip['anchor'], trip['positive'], trip['negative']]))

# ładowanie danych treningowych
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)

# przypisanie funkcji straty
train_loss = losses.TripletLoss(model=model)

In [38]:
%%timeit
# pomiar czasu:
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=3,               # 3-krotne przejście po danych
    warmup_steps=100,       # pierwsze 100 kroków wolnej nauki
    show_progress_bar=True  # pasek postępu
)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

KeyboardInterrupt:

In [ ]:
"""
15min

[897/897 03:16, Epoch 3/3]
Step	Training Loss
500	4.044029


[897/897 03:17, Epoch 3/3]
Step	Training Loss
500	3.972924


[897/897 03:20, Epoch 3/3]
Step	Training Loss
500	3.957050


[897/897 03:16, Epoch 3/3]
Step	Training Loss
500	3.934732


[897/897 03:17, Epoch 3/3]
Step	Training Loss
500	3.903447


"""

In [39]:
model.save('finetuned-model')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
import torch

In [44]:

def recommend_movies_finetuned(user_plot, top_n=5, list_only=False):

    global model

    # generowanie wektorów
    local_embeddings = model.encode(df['combined_text'].tolist(), convert_to_tensor=True).float()

    # kodowanie przekazanej fabuły
    query_embedding = model.encode([user_plot], convert_to_tensor=True).float()

    # obliczanie podobieństwa
    scores = model.similarity(query_embedding, local_embeddings)[0]

    # zmiana na numpy
    scores_np = scores.cpu().numpy()
    top_results = np.argsort(scores_np)[-top_n:][::-1]

    # wyniki
    print(f"\n[DOSTROJONY MODEL] Podany opis: '{user_plot}'\n")
    for idx in top_results:
        score = scores_np[idx]
        title = df.iloc[idx]['title']
        overview = df.iloc[idx]['overview']

        if not list_only:
            if len(overview) > 200:
                short_overview = overview[:200] + "..."
            else:
                short_overview = overview[:-1] if overview else ""
            print(f"Tytuł: {title} (Podobieństwo: {score:.2f})")
            print(f"Opis:  {short_overview}\n")
        else:
            print(f"Tytuł: {title} (Podobieństwo: {score:.2f})")

# 10. Testowanie dostrojonego modelu

In [45]:
# przykładowa fabuła
recommend_movies_finetuned("A group of scientists travel through time to prevent a disaster.")

[DOSTROJONY MODEL] Podany opis: 'A group of scientists travel through time to prevent a disaster.'

Tytuł: Def-Con 4 (Podobieństwo: 0.99)
Opis:  Two men and a woman circle the globe in a satellite armed with a nuclear device. The third world war breaks out, and a few months later the satellite crashes. They survive the crash but one man gets k...

Tytuł: Jumper (Podobieństwo: 0.99)
Opis:  David Rice is a man who knows no boundaries, a Jumper, born with the uncanny ability to teleport instantly to anywhere on Earth. When he discovers others like himself, David is thrust into a dangerous...

Tytuł: Mutant World (Podobieństwo: 0.99)
Opis:  A decade after a disastrous meteor impact wipes out most of society, a group of survivalists emerge to find themselves on a twisted version of the old Earth, with a nascent society besieged by vicious...

Tytuł: Death Calls (Podobieństwo: 0.99)
Opis:  An action-packed love story on the Mexican border featuring oppression, revenge, reincarnation and rebirth

Tytuł: Wolf (Podobieństwo: 0.99)
Opis:  Publisher Will Randall becomes a werewolf and has to fight to keep his job

In [46]:
recommend_movies_finetuned("A group of scientists travel through time to prevent a disaster.", top_n=20, list_only=True)

[DOSTROJONY MODEL] Podany opis: 'A group of scientists travel through time to prevent a disaster.'

Tytuł: Def-Con 4 (Podobieństwo: 0.99)
Tytuł: Jumper (Podobieństwo: 0.99)
Tytuł: Mutant World (Podobieństwo: 0.99)
Tytuł: Death Calls (Podobieństwo: 0.99)
Tytuł: Wolf (Podobieństwo: 0.99)
Tytuł: Transformers (Podobieństwo: 0.99)
Tytuł: The Iron Giant (Podobieństwo: 0.99)
Tytuł: The Angry Birds Movie (Podobieństwo: 0.99)
Tytuł: Show Boat (Podobieństwo: 0.99)
Tytuł: The Lost World: Jurassic Park (Podobieństwo: 0.99)
Tytuł: Anastasia (Podobieństwo: 0.99)
Tytuł: Only the Strong (Podobieństwo: 0.99)
Tytuł: The Good Dinosaur (Podobieństwo: 0.99)
Tytuł: The Book of Mormon Movie, Volume 1: The Journey (Podobieństwo: 0.99)
Tytuł: A LEGO Brickumentary (Podobieństwo: 0.99)
Tytuł: Steamboy (Podobieństwo: 0.99)
Tytuł: Lara Croft: Tomb Raider (Podobieństwo: 0.99)
Tytuł: Lost in Space (Podobieństwo: 0.99)
Tytuł: The Blood of Heroes (Podobieństwo: 0.99)
Tytuł: Shipwrecked (Podobieństwo: 0.99)

In [47]:
# testowanie rekomendowania kolejnych filmów z serii
# Harry Potter
user_plot = 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. \
He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard \
Lord Voldemort, who seeks to conquer the magical world and murdered Harry\'s parents when Harry was a baby.'
recommend_movies_finetuned(user_plot)

[DOSTROJONY MODEL] Podany opis: 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard Lord Voldemort, who seeks to conquer the magical world and murdered Harry's parents when Harry was a baby.'

Tytuł: Transformers (Podobieństwo: 1.00)
Opis:  Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots – the heroic Autobots and the evil Decepticons. Sam holds the clue to...

Tytuł: Jumper (Podobieństwo: 1.00)
Opis:  David Rice is a man who knows no boundaries, a Jumper, born with the uncanny ability to teleport instantly to anywhere on Earth. When he discovers others like himself, David is thrust into a dangerous...

Tytuł: The Lost World: Jurassic Park (Podobieństwo: 1.00)
Opis:  Four years after Jurassic Park's genetically bred dinosaurs ran amok, multimillionaire John Hammond shocks chaos theorist Ian Malcolm by revealing that Hammond has been breeding more beasties at a sec...

Tytuł: X-Men: Days of Future Past (Podobieństwo: 1.00)
Opis:  The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our...

Tytuł: Def-Con 4 (Podobieństwo: 1.00)
Opis:  Two men and a woman circle the globe in a satellite armed with a nuclear device. The third world war breaks out, and a few months later the satellite crashes. They survive the crash but one man gets k...

In [48]:
recommend_movies_finetuned(user_plot, top_n=20, list_only=True)

[DOSTROJONY MODEL] Podany opis: 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard Lord Voldemort, who seeks to conquer the magical world and murdered Harry's parents when Harry was a baby.'

Tytuł: Transformers (Podobieństwo: 1.00)
Tytuł: Jumper (Podobieństwo: 1.00)
Tytuł: The Lost World: Jurassic Park (Podobieństwo: 1.00)
Tytuł: X-Men: Days of Future Past (Podobieństwo: 1.00)
Tytuł: Def-Con 4 (Podobieństwo: 1.00)
Tytuł: The Blood of Heroes (Podobieństwo: 1.00)
Tytuł: The Angry Birds Movie (Podobieństwo: 1.00)
Tytuł: Lara Croft: Tomb Raider (Podobieństwo: 1.00)
Tytuł: Space Chimps (Podobieństwo: 1.00)
Tytuł: The Good Dinosaur (Podobieństwo: 1.00)
Tytuł: Death Calls (Podobieństwo: 1.00)
Tytuł: The Wolverine (Podobieństwo: 1.00)
Tytuł: Only the Strong (Podobieństwo: 1.00)
Tytuł: Lost in Space (Podobieństwo: 1.00)
Tytuł: Mutant World (Podobieństwo: 1.00)
Tytuł: Steamboy (Podobieństwo: 1.00)
Tytuł: Anastasia (Podobieństwo: 1.00)
Tytuł: Show Boat (Podobieństwo: 1.00)
Tytuł: The Crocodile Hunter: Collision Course (Podobieństwo: 1.00)
Tytuł: The Iron Giant (Podobieństwo: 0.99)

In [49]:
# Lord of the rings
user_plot = 'The Hobbit Frodo Baggins inherits the One Ring, an artifact of \
immense power created by the Dark Lord Sauron. To save Middle-earth, Frodo and \
eight companions—the Fellowship—embark on a perilous quest to Mount Doom in \
Mordor, the only place where the Ring can be destroyed'
recommend_movies_finetuned(user_plot)

[DOSTROJONY MODEL] Podany opis: 'The Hobbit Frodo Baggins inherits the One Ring, an artifact of immense power created by the Dark Lord Sauron. To save Middle-earth, Frodo and eight companions—the Fellowship—embark on a perilous quest to Mount Doom in Mordor, the only place where the Ring can be destroyed'

Tytuł: The Lord of the Rings: The Two Towers (Podobieństwo: 1.00)
Opis:  Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fell...

Tytuł: Harry Potter and the Philosopher's Stone (Podobieństwo: 1.00)
Opis:  Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School ...

Tytuł: U.F.O. (Podobieństwo: 1.00)
Opis:  A group of friends awake one morning to find all electricity and power shut off and an immense alien aircraft hovering in the air above their heads. Suddenly this regular group of friends is battling ...

Tytuł: The Bounty Hunter (Podobieństwo: 1.00)
Opis:  Milo Boyd is a bounty hunter whose latest gig is rather satisfying, as he finds out that the bail-skipper he must chase down is his own ex-wife, Nicole -- but she has no intention of getting nabbed wi...

Tytuł: The Scorpion King (Podobieństwo: 1.00)
Opis:  In ancient Egypt, peasant Mathayus is hired to exact revenge on the powerful Memnon and the sorceress Cassandra, who are ready to overtake Balthazar's village. Amid betrayals, thieves, abductions and ...

In [50]:
# James Bond
user_plot = 'James Bond travels to Jamaica to investigate the murder of a \
British agent. He discovers that a megalomaniacal scientist named Dr. No, \
a member of the criminal organization SPECTRE, is using a secret atomic reactor \
on the island of Crab Key to sabotage American space rocket launches'
recommend_movies_finetuned(user_plot)

[DOSTROJONY MODEL] Podany opis: 'James Bond travels to Jamaica to investigate the murder of a British agent. He discovers that a megalomaniacal scientist named Dr. No, a member of the criminal organization SPECTRE, is using a secret atomic reactor on the island of Crab Key to sabotage American space rocket launches'

Tytuł: Falcon Rising (Podobieństwo: 1.00)
Opis:  Chapman is an ex-marine in Brazil's slums, battling the yakuza outfit who attacked his sister and left her for dead

Tytuł: Star Wars (Podobieństwo: 1.00)
Opis:  Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the ...

Tytuł: Akira (Podobieństwo: 1.00)
Opis:  Childhood friends Tetsuo and Kaneda are pulled into the post-apocalyptic underworld of Neo-Tokyo and forced to fight for their very survival. Kaneda is a bike gang leader, and Tetsuo is a member of a ...

Tytuł: Ultramarines: A Warhammer 40,000 Movie (Podobieństwo: 1.00)
Opis:  A squad of Ultramarines answer a distress call from an Imperial Shrine World. A full Company of Imperial Fists was stationed there, but there is no answer from them. The squad investigates to find out...

Tytuł: Percy Jackson & the Olympians: The Lightning Thief (Podobieństwo: 1.00)
Opis:  Accident prone teenager, Percy discovers he's actually a demi-God, the son of Poseidon, and he is needed when Zeus' lightning is stolen. Percy must master his new found skills in order to prevent a wa...

In [51]:
# filmy Marvela
# Iron Man
user_plot = 'Billionaire industrialist Tony Stark is kidnapped by terrorists and \
forced to build a weapon. Instead, he creates a high-tech armored suit to escape. \
Returning home, Stark shuts down his weapons manufacturing and perfects the armor \
to fight global corruption, ultimately taking down his greedy business partner'
recommend_movies_finetuned(user_plot)

[DOSTROJONY MODEL] Podany opis: 'Billionaire industrialist Tony Stark is kidnapped by terrorists and forced to build a weapon. Instead, he creates a high-tech armored suit to escape. Returning home, Stark shuts down his weapons manufacturing and perfects the armor to fight global corruption, ultimately taking down his greedy business partner'

Tytuł: The Iron Giant (Podobieństwo: 1.00)
Opis:  In the small town of Rockwell, Maine in October 1957, a giant metal machine befriends a nine-year-old boy and ultimately finds its humanity by unselfishly saving people from their own fears and prejud...

Tytuł: The Wolverine (Podobieństwo: 1.00)
Opis:  Wolverine faces his ultimate nemesis - and tests of his physical, emotional, and mortal limits - in a life-changing voyage to modern-day Japan

Tytuł: Earth to Echo (Podobieństwo: 1.00)
Opis:  After a construction project begins digging in their neighborhood, best friends Tuck, Munch and Alex inexplicably begin to receive strange, encoded messages on their cell phones. Convinced something b...

Tytuł: The Adventures of Sharkboy and Lavagirl (Podobieństwo: 1.00)
Opis:  Everyone always knew that Max had a wild imagination, but no one believed that his wildest creations -- a boy raised by watchful great white sharks and a girl with the force of a volcano -- were real....

Tytuł: The Good Dinosaur (Podobieństwo: 1.00)
Opis:  An epic journey into the world of dinosaurs where an Apatosaurus named Arlo makes an unlikely human friend

# 11. Porównanie modeli

In [40]:
model_base_clean = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

model_ft_clean = model

# generowanie wektorów
embeddings_base_clean = model_base_clean.encode(df['combined_text'].tolist(), convert_to_tensor=True).float()

# generowanie wektorów
embeddings_ft_clean = model_ft_clean.encode(df['combined_text'].tolist(), convert_to_tensor=True).float()

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

=== KROK 2: GENEROWANIE EMBEDDINGÓW (MAP MAPOWANIA) ===
Generowanie wektorów dla modelu bazowego...
Generowanie wektorów dla modelu dostrojonego...

[SUKCES] Modele i wektory zostały poprawnie odizolowane!

In [55]:
# funkcja porównująca wyniki
def compare_to_dataframe(user_plot, top_n=5):

    # model bazowy
    query_emb_base = model_base_clean.encode([user_plot], convert_to_tensor=True).float()
    scores_base = model_base_clean.similarity(query_emb_base, embeddings_base_clean)[0].cpu().numpy()
    idx_base = np.argsort(scores_base)[-top_n:][::-1]

    # model dostrojony
    query_emb_ft = model_ft_clean.encode([user_plot], convert_to_tensor=True).float()
    scores_ft = model_ft_clean.similarity(query_emb_ft, embeddings_ft_clean)[0].cpu().numpy()
    idx_ft = np.argsort(scores_ft)[-top_n:][::-1]

    # struktura danych
    base_titles, base_scores = [], []
    ft_titles, ft_scores = [], []

    for i in range(top_n):
        # dane bazowe
        b_idx = idx_base[i]
        base_titles.append(df.iloc[b_idx]['title'])
        base_scores.append(round(float(scores_base[b_idx]), 4))

        # dane dostrojone
        ft_idx = idx_ft[i]
        ft_titles.append(df.iloc[ft_idx]['title'])
        ft_scores.append(round(float(scores_ft[ft_idx]), 4))

    # tworzenie df
    comparison_df = pd.DataFrame({
        'film': base_titles,
        'podobieństwo': base_scores,
        'film z dostrojonego modelu': ft_titles,
        'podobieństwo z dostrojonego': ft_scores
    })

    # indeksowanie
    comparison_df.index = np.arange(1, len(comparison_df) + 1)

    return comparison_df

# 12. Przykłady

In [56]:
# test 1: film kryminalny/akcji (Heat)
plot_heat = (
    "A meticulous career thief (Robert De Niro) and a relentless LAPD detective (Al Pacino) "
    "are locked in a deadly cat-and-mouse game across Los Angeles. While tracking a botched heist, "
    "both men realize they share a mutual respect and are fundamentally identical in their obsessive dedication."
)

df_heat = compare_to_dataframe(plot_heat, top_n=5)
display(df_heat)
print("\n")

# test 2: komedia romantyczna
plot_romance = "A romantic comedy about two people who live in New York and accidentally fall in love over Christmas."
df_romance = compare_to_dataframe(plot_romance, top_n=5)

display(df_romance)

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,The Town,0.5842,Jumper,0.9992
2,Kiss Kiss Bang Bang,0.4861,Transformers,0.9992
3,Parker,0.4822,The Iron Giant,0.9992
4,12 Rounds,0.4778,The Good Dinosaur,0.9992
5,American Hustle,0.4754,Lost in Space,0.9989

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,Love Actually,0.7466,Laws of Attraction,0.9999
2,New Year's Eve,0.7003,Intolerable Cruelty,0.9999
3,The Incredibly True Adventure of Two Girls In ...,0.6150,Neighbors,0.9999
4,The Best Man Holiday,0.6113,Waking Ned,0.9999
5,Never Again,0.6069,Bananas,0.9999

# 13. Porównanie rekomendacji

## Harry Potter

In [57]:
# testowanie rekomendowania kolejnych filmów z serii
# Harry Potter
user_plot = 'Harry Potter follows an orphaned boy who discovers he is a wizard at age 11. \
He attends Hogwarts, where he befriends Ron and Hermione. Together, they battle the dark wizard \
Lord Voldemort, who seeks to conquer the magical world and murdered Harry\'s parents when Harry was a baby.'
compare_to_dataframe(user_plot, top_n=30)

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,Harry Potter and the Philosopher's Stone,0.6603,Transformers,0.9964
2,Harry Potter and the Goblet of Fire,0.6389,Jumper,0.9962
3,Harry Potter and the Prisoner of Azkaban,0.5882,The Lost World: Jurassic Park,0.9959
4,Harry Potter and the Chamber of Secrets,0.5850,X-Men: Days of Future Past,0.9959
5,Harry Potter and the Half-Blood Prince,0.5480,Def-Con 4,0.9958
6,Harry Potter and the Order of the Phoenix,0.5262,The Blood of Heroes,0.9958
7,Pan's Labyrinth,0.4522,The Angry Birds Movie,0.9958
8,Disturbia,0.4417,Lara Croft: Tomb Raider,0.9958
9,Dude Where's My Dog?,0.4332,Space Chimps,0.9957
10,The Exorcist,0.4320,The Good Dinosaur,0.9957
11,Bogus,0.4249,Death Calls,0.9956
12,Something's Gotta Give,0.4107,The Wolverine,0.9955
13,St. Vincent,0.4099,Only the Strong,0.9955
14,Little Boy,0.4094,Lost in Space,0.9955
15,Heli,0.4093,Mutant World,0.9955
16,A Room for Romeo Brass,0.4078,Steamboy,0.9954
17,The Indian in the Cupboard,0.4026,Anastasia,0.9954
18,Martian Child,0.4000,Show Boat,0.9953
19,Boyhood,0.3986,The Crocodile Hunter: Collision Course,0.9951
20,Wish I Was Here,0.3965,The Iron Giant,0.9950
21,Pan,0.3950,The Hunger Games: Catching Fire,0.9949
22,Bad Grandpa,0.3940,Hancock,0.9949
23,Blue Car,0.3903,Blue Crush,0.9949
24,Loose Cannons,0.3772,"The Book of Mormon Movie, Volume 1: The Journey",0.9948
25,Arthur and the Invisibles,0.3766,Earth to Echo,0.9947
26,The Inkwell,0.3752,War,0.9947
27,Hesher,0.3744,Agent Cody Banks,0.9946
28,And Then Came Love,0.3706,Wolf,0.9944
29,Diary of a Wimpy Kid: Rodrick Rules,0.3670,Space Pirate Captain Harlock,0.9942
30,Home Alone,0.3647,The Adventures of Sharkboy and Lavagirl,0.9942

## Władca Pierścieni

In [58]:
# Lord of the rings
user_plot = 'The Hobbit Frodo Baggins inherits the One Ring, an artifact of \
immense power created by the Dark Lord Sauron. To save Middle-earth, Frodo and \
eight companions—the Fellowship—embark on a perilous quest to Mount Doom in \
Mordor, the only place where the Ring can be destroyed'
compare_to_dataframe(user_plot, top_n=30)

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,The Lord of the Rings: The Fellowship of the Ring,0.8768,The Lord of the Rings: The Two Towers,0.9987
2,The Lord of the Rings: The Return of the King,0.5941,Harry Potter and the Philosopher's Stone,0.9983
3,The Lord of the Rings: The Two Towers,0.5639,U.F.O.,0.9982
4,The Hobbit: An Unexpected Journey,0.5545,The Bounty Hunter,0.9982
5,The Hobbit: The Desolation of Smaug,0.5088,The Scorpion King,0.9982
6,The Hobbit: The Battle of the Five Armies,0.3849,Excessive Force,0.9981
7,Little Nicky,0.3438,Universal Soldier: The Return,0.9980
8,Warlock: The Armageddon,0.3246,Clash of the Titans,0.9980
9,"The Book of Mormon Movie, Volume 1: The Journey",0.3162,Digimon: The Movie,0.9980
10,Raging Bull,0.3093,The Legend of Tarzan,0.9980
11,Green Lantern,0.3074,Dark City,0.9979
12,Hellboy II: The Golden Army,0.3016,Epic,0.9979
13,Indiana Jones and the Temple of Doom,0.2879,Nerve,0.9979
14,Mirror Mirror,0.2793,I Am Number Four,0.9979
15,The Adventurer: The Curse of the Midas Box,0.2771,The 6th Day,0.9978
16,George and the Dragon,0.2756,Harry Potter and the Prisoner of Azkaban,0.9978
17,My Name Is Bruce,0.2752,The League of Extraordinary Gentlemen,0.9978
18,GoldenEye,0.2725,Warriors of Virtue,0.9978
19,Dragonslayer,0.2697,Prince of Persia: The Sands of Time,0.9978
20,Wuthering Heights,0.2690,Nancy Drew,0.9977
21,The Rite,0.2646,Skyline,0.9977
22,Conan the Barbarian,0.2642,Tomorrow Never Dies,0.9977
23,How to Train Your Dragon,0.2584,The Black Hole,0.9977
24,DragonHeart,0.2564,Mad Max Beyond Thunderdome,0.9977
25,Thor,0.2501,The Matrix,0.9975
26,The Tale of Despereaux,0.2498,The Hobbit: An Unexpected Journey,0.9975
27,Shalako,0.2490,The Secret Life of Pets,0.9974
28,The Last Temptation of Christ,0.2473,X-Men: Apocalypse,0.9974
29,Big Trouble in Little China,0.2471,Rodeo Girl,0.9974
30,Dungeons & Dragons: Wrath of the Dragon God,0.2469,Steel,0.9974

## James Bond

In [59]:
# James Bond
user_plot = 'James Bond travels to Jamaica to investigate the murder of a \
British agent. He discovers that a megalomaniacal scientist named Dr. No, \
a member of the criminal organization SPECTRE, is using a secret atomic reactor \
on the island of Crab Key to sabotage American space rocket launches'
compare_to_dataframe(user_plot, top_n=30)

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,Dr. No,0.7405,Falcon Rising,0.9989
2,Octopussy,0.6674,Star Wars,0.9988
3,Live and Let Die,0.6448,Akira,0.9987
4,The Living Daylights,0.6254,"Ultramarines: A Warhammer 40,000 Movie",0.9986
5,Quantum of Solace,0.5660,Percy Jackson & the Olympians: The Lightning T...,0.9986
6,Never Say Never Again,0.5651,The Lone Ranger,0.9986
7,You Only Live Twice,0.5597,Pirates of the Caribbean: At World's End,0.9985
8,Die Another Day,0.5421,Captain America: The First Avenger,0.9985
9,From Russia with Love,0.5396,The Lord of the Rings: The Fellowship of the Ring,0.9985
10,For Your Eyes Only,0.5310,Six-String Samurai,0.9985
11,GoldenEye,0.5223,The Matrix Revolutions,0.9985
12,Thunderball,0.5175,Hum To Mohabbat Karega,0.9984
13,Spectre,0.5130,Æon Flux,0.9984
14,A View to a Kill,0.5066,Underworld: Evolution,0.9984
15,Licence to Kill,0.5063,Criminal,0.9984
16,The Spy Who Loved Me,0.5021,X-Men,0.9984
17,Moonraker,0.4996,Swordfish,0.9983
18,The World Is Not Enough,0.4889,Shalako,0.9983
19,Goldfinger,0.4839,Dragonball Evolution,0.9983
20,The Secret,0.4770,Running Forever,0.9983
21,Diamonds Are Forever,0.4747,End of Days,0.9983
22,On Her Majesty's Secret Service,0.4744,Allegiant,0.9983
23,Tinker Tailor Soldier Spy,0.4670,The Fifth Element,0.9982
24,The Negotiator,0.4659,Avengers: Age of Ultron,0.9982
25,Live Free or Die Hard,0.4636,Megiddo: The Omega Code 2,0.9982
26,The Constant Gardener,0.4562,Pirates of the Caribbean: On Stranger Tides,0.9982
27,John Q,0.4534,Frozen,0.9982
28,The Tailor of Panama,0.4532,The Chronicles of Riddick,0.9981
29,The Bourne Identity,0.4527,Transformers: Revenge of the Fallen,0.9981
30,Criminal,0.4485,15 Minutes,0.9981

## Filmy Marvela

In [60]:
# filmy Marvela
# Iron Man
user_plot = 'Billionaire industrialist Tony Stark is kidnapped by terrorists and \
forced to build a weapon. Instead, he creates a high-tech armored suit to escape. \
Returning home, Stark shuts down his weapons manufacturing and perfects the armor \
to fight global corruption, ultimately taking down his greedy business partner'
compare_to_dataframe(user_plot, top_n=30)

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,Iron Man,0.7174,The Iron Giant,0.9992
2,Iron Man 2,0.6352,The Wolverine,0.9990
3,Lords of London,0.5435,Earth to Echo,0.9990
4,Iron Man 3,0.5244,The Adventures of Sharkboy and Lavagirl,0.9989
5,Avengers: Age of Ultron,0.5123,The Good Dinosaur,0.9987
6,Steel,0.4972,Yeh Jawaani Hai Deewani,0.9985
7,Scarface,0.4818,Madagascar,0.9985
8,Cradle 2 the Grave,0.4745,Show Boat,0.9985
9,Machete Kills,0.4500,Transformers,0.9985
10,Shinjuku Incident,0.4233,Jumper,0.9983
11,King's Ransom,0.4168,Barbarella,0.9983
12,Men of War,0.4165,The Little Prince,0.9982
13,The Rock,0.4156,The Blood of My Brother: A Story of Death in Iraq,0.9982
14,Super,0.4089,Spider-Man,0.9980
15,The Avengers,0.3998,Lost in Space,0.9980
16,Captain America: The Winter Soldier,0.3977,Benji,0.9979
17,Machine Gun McCain,0.3938,Mutant World,0.9979
18,Hamlet,0.3890,The Angry Birds Movie,0.9978
19,MacGruber,0.3873,Stardust,0.9978
20,The Man with the Golden Gun,0.3867,Death Calls,0.9977
21,Jonah Hex,0.3842,The Crocodile Hunter: Collision Course,0.9977
22,Friday the 13th: A New Beginning,0.3828,Shipwrecked,0.9975
23,Megamind,0.3799,Savva. Heart of the Warrior,0.9974
24,Superman IV: The Quest for Peace,0.3798,Space Chimps,0.9973
25,Armored,0.3770,The Hunger Games: Catching Fire,0.9973
26,Olympus Has Fallen,0.3758,Born to Fly: Elizabeth Streb vs. Gravity,0.9971
27,In Her Line of Fire,0.3755,"Peace, Propaganda & the Promised Land",0.9971
28,Commando,0.3734,Blackthorn,0.9971
29,Die Hard 2,0.3702,Def-Con 4,0.9970
30,The Matrix Reloaded,0.3676,She Wore a Yellow Ribbon,0.9970

## Love Actually

In [61]:
user_plot = "Love Actually is a 2003 British holiday romantic comedy \
that weaves together ten distinct stories of love, loss, and longing. \
Set in London during the frantic weeks leading up to Christmas, \
the film explores the complexities of relationships through a massive, \
interconnected cast of characters."
compare_to_dataframe(user_plot, top_n=30)

,film,podobieństwo,film z dostrojonego modelu,podobieństwo z dostrojonego
1,Love Actually,0.7088,Cars,0.9994
2,About Last Night,0.5827,Wreck-It Ralph,0.9994
3,The Incredibly True Adventure of Two Girls In ...,0.5819,All About the Benjamins,0.9994
4,"Lovely, Still",0.5817,The Men Who Stare at Goats,0.9993
5,The Lovers,0.5701,Little Shop of Horrors,0.9993
6,New Year's Eve,0.5684,3 Ninjas Kick Back,0.9993
7,Midnight in Paris,0.5578,Ice Age,0.9993
8,Before Sunrise,0.5566,Mortdecai,0.9993
9,Housefull,0.5546,Inspector Gadget,0.9993
10,The Broken Hearts Club: A Romantic Comedy,0.5522,Ravenous,0.9993
11,One Day,0.5501,Teeth,0.9993
12,Laws of Attraction,0.5487,Fled,0.9993
13,From Justin to Kelly,0.5478,The Lego Movie,0.9993
14,Love and Other Catastrophes,0.5451,The Pink Panther,0.9992
15,Fly Me to the Moon,0.5432,Grabbers,0.9992
16,Lars and the Real Girl,0.5430,The Nut Job,0.9992
17,Notting Hill,0.5403,Without a Paddle,0.9992
18,Closer,0.5402,Tucker and Dale vs Evil,0.9992
19,Next Stop Wonderland,0.5378,Rio 2,0.9992
20,Shallow Hal,0.5352,Ice Age: The Meltdown,0.9992
21,16 to Life,0.5352,Arachnophobia,0.9992
22,Never Again,0.5350,ParaNorman,0.9992
23,Mambo Italiano,0.5336,Alpha and Omega: The Legend of the Saw Tooth Cave,0.9992
24,Why Did I Get Married?,0.5320,Jurassic Park,0.9991
25,The Rules of Attraction,0.5275,The Return of the Living Dead,0.9991
26,The Notebook,0.5271,Road Trip,0.9991
27,Boynton Beach Club,0.5269,Three Kings,0.9991
28,The Bubble,0.5227,Man of the House,0.9990
29,Veer-Zaara,0.5223,Escape from Planet Earth,0.9990
30,London,0.5223,Shanghai Noon,0.9990

Wybrana metoda dostrajania okazała się przeciwskuteczna. Rekomendacje proponowane przez pierwszy model były dużo bardziej podobne do przedstawionego filmu.